### ISSUE TITLE
Support Proposal Creation Whitelists

### ISSUE THREAD

**Issue by mudrila** [decent-dao/fractal-contracts#119]
New feature: allow a DAO to opt-in to the concept of "whitelisting" who can create proposals on the DAO.

This feature should tie into "Roles", and the "whitelist" should be created by selecting which Roles on the DAO are authorized to create proposals.

From an implementation point of view, I believe we need to create new Azorius Strategies to support this functionality.

As a refresher, Azorius:
- has one or more "Strategies" attached to it
- is where new proposals are posted to, through the `submitProposal` function
  - a new proposal targets a specific (attached) strategy via its function parameters
- is where proposals are executed from, through the `executeProposal` function

"Strategies" are smart contracts which implement the `IBaseStrategy` interface, which is implemented in the abstract `BaseStrategy` contract which all strategies inherit from.

As a refresher, each Strategy:
1. implements logic to authorize that a given address is allowed to create a proposal targeting said strategy
2. implements logic to determine when a given proposal is "over" and won't accept any more votes
3. implements logic to determine if a given proposal has "passed" or not
   - (this includes all of the "voting" logic)

With that context, I hope it's straightforward to see that our approach to implement a "whitelist" of who can create proposals, should be through the implementation of new Strategy contracts.

We want to limit "who" can create proposals to Roles on a whitelist, so we must create a strategy that implements this! Given the list of strategy responsibilities above, we need to modify 1. It's assumed that we still want 2. and 3. to keep the same implementation as current ERC20 or ERC721 strategy implementations.

As of now I believe this is most easily achieved by creating new strategies which inherit from `LinearERC20Voting` and `LinearERC721Voting`, and override the `isProposer` function.

Risks

As we move down the "decentralization" curve, we move up the "risk" curve.

Consider a DAO which has chosen to activate Roles Whitelisting for Proposal Creation. They want _only_ that member who holds a specific Role to be able to create proposals. But then imagine that individual dies, and their private key is lost. If there is no contingency plan, the DAO will be effectively frozen and locked forever.

It would be prudent to create an _additional_ Strategy, which perhaps is always added to all DAOs by default, which has hardcoded logic that implements "add another arbitrary strategy to Azorius". This strategy might return `true` for _any_ address passed into `isProposer`, which would allow anyone to create a proposal to add an additional strategy, in this worst-case scenario. Some outstanding questions still:
- Who would be able to vote on it?
  - More generally, does this "safety net strategy" only make sense on "token voting DAOs"?
  - Like, does there still need to be a governance token to answer the question of "who can vote on this proposal"?
- When would a proposal from this strategy end? Should we simply "duplicate" the configuration from the main "whitelisted proposal creation" strategy?

**Comment by adamgall** [comment]
This is completed
