### ISSUE TITLE
Add tests for Usul functionality to `Fractal-Usul`

### ISSUE THREAD

**Issue by mudrila** [decent-dao/fractal-contracts#16]

**Comment by herbig** [comment]
@mudrila what were you planning for this? To test the methods we overrode on Usul, or to test the whole of Usul?

I'm not sure we need to test Usul itself unless we've modified the functionality.

**Comment by herbig** [comment]
ah, cool I didn't realize they didn't have any tests.

Yeah we can bring this back after the holidays
