### ISSUE TITLE
Deploy NFT Strategy to Mainnet and Polygon

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-contracts#70]
These contracts haven't been audited, and are only available on the frontend for Goerli at the moment:

- LinearERC721Voting
- ERC721FreezeVoting

We may have a mini audit, or bug bounty before deploying them to production, after which the frontend will also need to be updated to support it.

**Comment by adamgall** [comment]
deployed ERC721 contracts to mainnet and polygon
