### ISSUE TITLE
Deploy Fractal contracts to Base Sepolia

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-contracts#74]
This issue exists to track the work involved with deploying Fractal's contracts onto Base and Base Sepolia.

Related to:
- `interface`: https://github.com/decent-dao/fractal-interface/issues/1460
- `subgraph`: https://github.com/decent-dao/fractal-subgraph/issues/9

**Comment by dacebt** [comment]
Update: Currently Deploying to Base Sepolia.

Once testing has been completed, work will beging to deploy to Base mainnet

**Comment by adamgall** [comment]
This is completed, nice job @Da-Colon !
