### ISSUE TITLE
Add `MeetsQuorum` to `LinearERC721Voting.sol`

### ISSUE THREAD

**Issue by dacebt** [decent-dao/fractal-contracts#75]
To ensure that quorum is calculated properly across platforms (Onchain or via the frontend). We should abstract the logic for calculating ERC721 current quorum from the `isPassed` function 

```sol
    /** @inheritdoc BaseStrategy*/
    function isPassed(uint32 _proposalId) public view override returns (bool) {
        return (
            block.number > proposalVotes[_proposalId].votingEndBlock && // voting period has ended
            quorumThreshold <= proposalVotes[_proposalId].yesVotes + proposalVotes[_proposalId].abstainVotes && // yes + abstain votes meets the quorum
            meetsBasis(proposalVotes[_proposalId].yesVotes, proposalVotes[_proposalId].noVotes) // yes votes meets the basis
        );
    }
```

To be specific this section should be moved to its own `meetsQuorum` function. 

```sol
quorumThreshold <= proposalVotes[_proposalId].yesVotes + proposalVotes[_proposalId].abstainVotes`
```

**Comment by dacebt** [comment]
@adamgall Implementing `meetsQuorum` from the linear strategy I had a thought. currently this function only takes in totalSupply, yes votes, abstain votes as arguments.

Does this affect any future changes by a DAO to change this via a proposal?

**Comment by adamgall** [comment]
Stale, closing
