### ISSUE TITLE
Upgrade Package dependencies

### ISSUE THREAD

**Issue by dacebt** [decent-dao/fractal-contracts#78]
After some discussion, We could benefit from spending some time upgrading the dependencies of this project. 

- Bring `fractal-contracts` repository up to date with current tooling
  - Current `hardhat`
  - `ethers-v6`
- Replace the depreciated `@gnosis.pm` package with the latest from Safe
- Remove everything except `deployments` artifacts from published NPM packages

**Comment by adamgall** [comment]
Is it such a bad thing to upgrade ethers to v6?

**Comment by dacebt** [comment]
Not at all. @adamgall Should I rename this to Upgrade Hardhat and its dependencies? Since you have a separate card for fixing the tests?

Also could be worth while to replace the `@gnosis.pm/~` dependencies since its been depreciated.

**Comment by adamgall** [comment]
Oh yeah, hmm. Yeah make this card specific for updating packages and bringing the repo up to date. I'll use that other card I opened specifically for removing the live network as a test suite dependency.

**Comment by adamgall** [comment]
> Not at all. @adamgall Should I rename this to Upgrade Hardhat and its dependencies? Since you have a separate card for fixing the tests?
> 
> Also could be worth while to replace the `@gnosis.pm/~` dependencies since its been depreciated.

Oh yeah, hmm. Yeah make this card specific for updating packages and bringing the repo up to date. I'll use that other card I opened specifically for removing the live network as a test suite dependency.
